recipe: default.v1
assistant_id: books_bot
language: ru

pipeline:
   - name: WhitespaceTokenizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 15
   - name: DIETClassifier
     epochs: 250
     constrain_similarities: true
   - name: EntitySynonymMapper

policies:
   - name: MemoizationPolicy
   - name: RulePolicy
     max_history: 10
   - name: UnexpecTEDIntentPolicy
     max_history: 18
     epochs: 100
   - name: TEDPolicy
     max_history: 18
     epochs: 250
     constrain_similarities: true
