recipe: default.v1
assistant_id: books_bot
language: ru

pipeline:
   - name: WhitespaceTokenizer
     case_sensitive: False
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 15
   - name: DIETClassifier
     epochs: 300
     constrain_similarities: True
   - name: EntitySynonymMapper

policies:
   - name: MemoizationPolicy
     max_history: 4
     epochs: 300
   - name: RulePolicy
     core_fallback_threshold: 0.7
     core_fallback_action_name: action_default_fallback
     enable_fallback_prediction: true
#     max_history: 10
#   - name: UnexpecTEDIntentPolicy
#     max_history: 18
#     epochs: 100
   - name: TEDPolicy
     max_history: 4
     epochs: 300
     constrain_similarities: True
